# This is a basic workflow to help you get started with Actions

name: Build and Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # npm install gh-pages --save
      # rm -rf node_modules package-lock.json
      # npm cache clean --force
      - name: Checkout
        uses: actions/checkout@v2.3.1
          
      - name: Build
        run: |
          npm install
          cd swe_portfolio
          npm install
          CI=false 
          npm run-script build
        env:
          REACT_APP_GITHUB_TOKEN:  ${{ secrets.REACT_APP_GITHUB_TOKEN }}

      # Runs a set of commands using the runners shell
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
          BRANCH: gh-pages
          FOLDER: swe_portfolio/build





